name: Deploy static site to VPS

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ── 1. Забираем репозиторий ───────────────────────
      - name: Checkout repo
        uses: actions/checkout@v4

      # ── 2. Копируем файлы на сервер ───────────────────
      - name: Copy files via rsync
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          SERVER_IP:       ${{ secrets.SERVER_IP }}
          SERVER_USER:     ${{ secrets.SERVER_USER }}
        run: |
          # кладём приватный ключ
          install -m 600 -D /dev/null ~/.ssh/id_ed25519
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          
          # добавляем хост‑ключ сервера
          ssh-keyscan -H "$SERVER_IP" >> ~/.ssh/known_hosts
          
          # деплой в /var/www/mirrora
          rsync -av --delete --exclude='.git/' ./ \
            "$SERVER_USER@$SERVER_IP:/var/www/mirrora"

      # ── 3. Перезагружаем Nginx ─────────────────────────
      - name: Reload Nginx
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
          SERVER_IP:       ${{ secrets.SERVER_IP }}
          SERVER_USER:     ${{ secrets.SERVER_USER }}
        run: |
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh -o StrictHostKeyChecking=no "$SERVER_USER@$SERVER_IP" \
              "sudo systemctl reload nginx"
